import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation strings
const translations = {
  en: {
    // Header
    home: 'Home',
    detectZone: 'DetectZone',
    previousAnalysis: 'Previous Analysis',
    pricing: 'Pricing',
    help: 'Help',
    login: 'Login',
    signup: 'Sign Up',
    
    // Homepage
    heroTitle: 'Advanced AI-Powered Deepfake Detection',
    heroSubtitle: 'Verify media authenticity with real-time analysis and professional forensic reports using state-of-the-art transformer models.',
    tryDemo: 'Try Demo',
    getStarted: 'Get Started',
    aboutTitle: 'About DeepXpose',
    aboutText: 'DeepXpose leverages cutting-edge AI technology to detect manipulated videos with 96.8% accuracy. Our multimodal approach combines facial analysis, temporal consistency checks, and audio-visual synchronization for comprehensive deepfake detection.',
    
    // Features
    featuresTitle: 'How It Works',
    feature1Title: 'Upload & Analyze',
    feature1Text: 'Upload your video files for instant AI-powered analysis',
    feature2Title: 'AI Processing', 
    feature2Text: 'Advanced transformer models process and analyze every frame',
    feature3Title: 'Get Results',
    feature3Text: 'Receive detailed reports with confidence scores and forensic data',
    
    // Team
    teamTitle: 'Created by',
    teamText: 'Developed by Amani Albarazi, Bushra Alshehri, and Maram Alhusami',
    courseInfo: 'CS 4174 Senior Project',
    supervisor: 'Supervisor: Dr. Fidaa Abed',
    instructor: 'Instructor: Dr. Naila Marir',
    
    // Footer
    termsOfService: 'Terms of Service',
    privacy: 'Privacy Policy',
    contact: 'Contact',
    copyright: '© 2025 DeepXpose. All rights reserved.',
    
    // DetectZone
    uploadTitle: 'Upload Video for Analysis',
    uploadSubtitle: 'Drag and drop your video file or click to browse',
    analyzing: 'Analyzing...',
    resultsTitle: 'Analysis Results',
    confidence: 'Confidence',
    processingTime: 'Processing Time',
    generateReport: 'Generate Report',
    
    // Analysis results
    real: 'REAL',
    fake: 'FAKE', 
    riskLow: 'Low Risk',
    riskMedium: 'Medium Risk',
    riskHigh: 'High Risk',
    
    // Pricing
    pricingTitle: 'Choose Your Plan',
    pricingSubtitle: 'Select the perfect plan for your deepfake detection needs',
    month: '/month',
    popular: 'Popular',
    suitable: 'Suitable for',
    
    // Help
    helpTitle: 'Frequently Asked Questions',
    helpSubtitle: 'Find answers to common questions about DeepXpose',
    
    // Additional common text
    accuracyRate: 'Accuracy Rate',
    avgAnalysis: 'Avg Analysis',
    videosAnalyzed: 'Videos Analyzed',
    trustedSecurity: 'Trusted Security',
    trustedSecurityDesc: 'End-to-end encrypted processing with automatic data deletion',
    lightningFast: 'Lightning Fast',
    lightningFastDesc: 'Real-time analysis with results in under 3 seconds',
    aiPowered: 'AI-Powered',
    aiPoweredDesc: 'Advanced transformer models with 96.8% accuracy rate',
    detailedReports: 'Detailed Reports',
    detailedReportsDesc: 'Comprehensive forensic analysis with exportable formats',
    welcomeBack: 'Welcome Back',
    welcomeBackDesc: 'Sign in to your DeepXpose account to continue analyzing videos',
    createAccount: 'Create Account',
    createAccountDesc: 'Join DeepXpose to start analyzing videos for deepfake manipulation',
    continueWithGoogle: 'Continue with Google',
    signUpWithGoogle: 'Sign up with Google',
    emailAddress: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    accountType: 'Account Type',
    organization: 'Organization (Optional)',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot your password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signUpForFree: 'Sign up for free',
    signInHere: 'Sign in here',
    freeTrialIncluded: 'Free Trial Included',
    freeTrialDesc: 'Get 5 free video analyses to test our platform. No credit card required.',
    endUser: 'End User - Individual Analysis',
    investigator: 'Investigator - Professional Forensics',
    termsAgreement: 'By creating an account, you agree to our',
    and: 'and',
    chooseFile: 'Choose File',
    supportedFormats: 'Supported formats: MP4, MOV, AVI, MKV, WebM',
    uploadProgress: '% uploaded',
    viewDetails: 'View Details',
    report: 'Report',
    artifactsDetected: 'Artifacts Detected',
    temporalIssues: 'Temporal Issues',
    faceRegions: 'Face Regions',
    analyzeAnotherVideo: 'Analyze Another Video',
    newAnalysis: 'New Analysis',
    totalAnalyses: 'Total Analyses',
    analysesRemaining: 'Analyses Remaining',
    subscription: 'Subscription',
    searchByFilename: 'Search by filename...',
    filterByResult: 'Filter by result',
    allResults: 'All Results',
    fakeOnly: 'Fake Only',
    realOnly: 'Real Only',
    sortBy: 'Sort by',
    newestFirst: 'Newest First',
    oldestFirst: 'Oldest First',
    confidenceSort: 'Confidence',
    filename: 'Filename',
    clear: 'Clear',
    noAnalysisFound: 'No Analysis Found',
    noMatchingFilters: 'No analyses match your current filters.',
    noAnalysisYet: "You haven't analyzed any videos yet.",
    analyzeFirstVideo: 'Analyze Your First Video',
    
    // Additional DetectZone and page-specific translations
    uploadingFile: 'Uploading File',
    analyzing: 'Analyzing...',
    manipulationIndicators: 'Manipulation Indicators',
    forensicReport: 'Forensic Analysis Report',
    executiveSummary: 'Executive Summary',
    technicalFindings: 'Technical Findings',
    recommendations: 'Recommendations',
    downloadReport: 'Download PDF Report',
    generating: 'Generating...',
    // Report Generation
    reportGeneration: 'Forensic Report Generation',
    generatingReport: 'Generating Report...',
    reportReady: 'Report Ready',
    downloadPDF: 'Download PDF Report',
    backToDetect: 'Back to DetectZone',
    noAnalysisData: 'No Analysis Data',
    completeAnalysis: 'Please complete a video analysis first.',
    analysisOverview: 'Analysis Overview',
    analystInfo: 'Analyst Information',
    analystName: 'Analyst Name',
    role: 'Role',
    reportGenerated: 'Report Generated',
    analysisMetadata: 'Analysis Metadata',
    reportVersion: 'Report Version',
    analysisEngine: 'Analysis Engine',
    reportId: 'Report ID',
    generatedAt: 'Generated At',
    // Footer translations
    madeWithLove: 'Made with ❤️ for digital trust and media authenticity',
    quickLinks: 'Quick Links',

    // Nav extra
    trendingAnalysis: 'Trending Analysis',
    dashboard: 'Dashboard',
    logout: 'Logout',

    // Home extra
    howItWorksSubtitle: 'Our AI-powered system processes videos through multiple layers of analysis to detect deepfake manipulation.',

    // Trending page
    trendingSubtitle: 'Analyze viral videos from social media platforms for deepfake manipulation and authenticity verification using AI-powered detection.',
    realtimeAIDetection: 'Real-time AI Detection',
    liveSocialMedia: 'Live Social Media',
    trendingContent: 'Trending Content',
    loadingTrendingVideos: 'Loading Trending Videos',
    loadingTrendingDesc: 'Fetching the latest viral content from social media platforms...',
    analyzingVideoContent: 'Analyzing Video Content',
    processingWithAI: 'Processing with AI detection models...',
    analysisIdLabel: 'Analysis ID:',
    keyFindingsLabel: 'Key findings:',
    processingTimeLabel: 'Processing time:',
    checkAuthenticity: 'Check Authenticity',
    reanalyze: 'Re-analyze',
    noVideosFound: 'No Videos Found',
    noVideosDesc: 'No trending videos available for the selected platform. Try switching to a different filter.',
    howTrendingWorks: 'How Trending Analysis Works',
    realtimeMonitoring: 'Real-time Monitoring',
    realtimeMonitoringDesc: 'We continuously monitor trending content across major social media platforms.',
    aiAnalysisStep: 'AI Analysis',
    aiAnalysisStepDesc: 'Advanced transformer models analyze each video for manipulation indicators.',
    instantResultsStep: 'Instant Results',
    instantResultsStepDesc: 'Get immediate authenticity verification with confidence scores and risk assessment.',
    fakeLabel: '❌ Fake',
    realLabel: '✅ Real',
    fakeMessage: 'This video shows signs of manipulation.',
    realMessage: 'This video appears authentic.',
    viewReport: 'View Report',
    loginToCheck: 'Please log in to check video authenticity. Redirecting to login...',
    analysisFailed: 'Analysis failed. Please try again.',
    failedToLoadVideos: 'Failed to load trending videos. Please try again.',
    retry: 'Retry',

    // Help page
    liveChat: 'Live Chat',
    liveChatDesc: 'Get instant help from our support team',
    startChat: 'Start Chat',
    emailSupport: 'Email Support',
    emailSupportDesc: 'Send us a detailed message',
    sendEmail: 'Send Email',
    phoneSupport: 'Phone Support',
    phoneSupportDesc: 'Talk directly with our experts',
    callUs: 'Call Us',
    searchHelpPlaceholder: 'Search help articles and FAQs...',
    noResultsFound: 'No Results Found',
    noResultsDesc: 'Try adjusting your search terms or browse our help categories.',
    helpCategories: 'Help Categories',
    stillNeedHelp: 'Still Need Help?',
    stillNeedHelpDesc: 'Our support team is available 24/7 to assist you with any questions or issues.',
    emailLabel: 'Email',
    responseWithin2h: 'Response within 2 hours',
    available247: 'Available 24/7',
    instantResponse: 'Instant response',
    phoneLabel: 'Phone',
    phoneHours: 'Mon-Fri, 9am-6pm PST',
    emergencySupport: 'Emergency Support',
    emergencySupportDesc: 'For critical security issues or urgent forensic analysis needs, contact our emergency support line.',
    emergencyContact: 'Emergency Contact',
    catGettingStarted: 'Getting Started',
    catGettingStartedDesc: 'Learn the basics of DeepXpose',
    catTechDocs: 'Technical Documentation',
    catTechDocsDesc: 'In-depth technical resources',
    catSecurity: 'Security & Privacy',
    catSecurityDesc: 'Data protection and security',
    catPerformance: 'Performance & Optimization',
    catPerformanceDesc: 'Optimize your analysis workflow',
    art1: 'How to create your first analysis',
    art2: 'Understanding confidence scores',
    art3: 'Supported video formats and sizes',
    art4: 'Account setup and verification',
    art5: 'API documentation and examples',
    art6: 'Integration guide for developers',
    art7: 'Understanding detection algorithms',
    art8: 'Custom reporting formats',
    art9: 'How we protect your data',
    art10: 'GDPR compliance information',
    art11: 'Data retention policies',
    art12: 'Security best practices',
    art13: 'Improving processing speeds',
    art14: 'File optimization tips',
    art15: 'Batch processing guidelines',
    art16: 'Plan optimization recommendations',

    // Form placeholders & misc
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    enterFullName: 'Enter your full name',
    selectRole: 'Select your role',
    enterOrganization: 'Enter your organization',
    createPassword: 'Create a password',
    confirmYourPassword: 'Confirm your password',
    signingIn: 'Signing In...',
    creatingAccount: 'Creating Account...',
    viewSampleReport: 'View Sample Report',
    tryFreeDemo: 'Try Free Demo',
    startFreeTrial: 'Start Free Trial',
    startDemoAnalysis: 'Start Demo Analysis',
    signUpNow: 'Sign Up Now',
    accessRequired: 'Access Required',
    accessRequiredDesc: 'Please log in to view your analysis history.',
    previousAnalysisDesc: 'View and manage your deepfake detection analysis history',
    tryBeforeSubscribe: 'Try Before You Subscribe',
    tryBeforeSubscribeDesc: 'Test our deepfake detection technology with a free demo',
    contactSales: 'Contact Sales',
    analysesIncludedSuffix: 'analyses included',
    demoAccount: 'Demo Account:',
    demoFeature: 'Demo Feature',
    tryDemoTitle: 'Try DeepXpose Demo',
    tryDemoSubtitle: 'Experience our AI-powered deepfake detection technology with this interactive demo. See how DeepXpose analyzes videos for manipulation indicators.',
    runDemoAgain: 'Run Demo Again',
    fileName: 'File Name:',
    fileSize: 'File Size:',
    analysisComplete: 'Analysis Complete',
    analysisCompleteEndUser: 'Your video analysis is complete. Generate a detailed report below.',
    analysisCompleteInvestigator: 'Professional forensic analysis complete. Generate comprehensive report.',
    manipulationIndicatorsDetected: 'Manipulation Indicators Detected',
    upgradeToInvestigator: 'Upgrade to Investigator for advanced forensic features',
    faq1Q: 'How accurate is DeepXpose in detecting deepfakes?',
    faq1A: 'DeepXpose achieves 96.8% accuracy on standard benchmarks using state-of-the-art transformer models. Our system combines facial analysis, temporal consistency checks, and audio-visual synchronization to provide comprehensive detection.',
    faq2Q: 'What video formats are supported?',
    faq2A: 'We support all major video formats including MP4, MOV, AVI, MKV, and WebM. Maximum file size is 500MB for Basic plan, 2GB for Professional plan, and unlimited for Enterprise.',
    faq3Q: 'How long does analysis take?',
    faq3A: 'Analysis time depends on video length and plan type. Basic plan: ~3-5 seconds per minute of video. Professional plan: ~1-2 seconds per minute with priority processing.',
    faq4Q: 'Is my data secure and private?',
    faq4A: 'Yes, all uploaded videos are processed securely and automatically deleted after 30 days. We use end-to-end encryption and comply with international privacy standards including GDPR.',
    faq5Q: 'Can I integrate DeepXpose with my existing systems?',
    faq5A: 'Professional and Enterprise plans include API access for seamless integration. We provide comprehensive documentation and support for custom integrations.'
  },
  ar: {
    // Header - Arabic
    home: 'الرئيسية',
    detectZone: 'منطقة الكشف',
    previousAnalysis: 'التحليلات السابقة', 
    pricing: 'الأسعار',
    help: 'المساعدة',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    
    // Homepage - Arabic
    heroTitle: 'نظام متقدم مدعوم بالذكاء الاصطناعي لكشف التزييف العميق',
    heroSubtitle: 'تحقق من صحة الوسائط مع التحليل الفوري والتقارير الشرعية المهنية باستخدام أحدث نماذج المحولات.',
    tryDemo: 'جرب العرض التوضيحي',
    getStarted: 'ابدأ الآن',
    aboutTitle: 'حول DeepXpose',
    aboutText: 'يستفيد DeepXpose من تقنية الذكاء الاصطناعي المتطورة لكشف مقاطع الفيديو المتلاعب بها بدقة 96.8%. نهجنا متعدد الوسائط يجمع بين تحليل الوجه وفحوصات الاتساق الزمني ومزامنة الصوت والصورة للكشف الشامل عن التزييف العميق.',
    
    // Features - Arabic
    featuresTitle: 'كيف يعمل',
    feature1Title: 'ارفع وحلل',
    feature1Text: 'ارفع ملفات الفيديو الخاصة بك للتحليل الفوري المدعوم بالذكاء الاصطناعي',
    feature2Title: 'معالجة الذكاء الاصطناعي',
    feature2Text: 'نماذج المحولات المتقدمة تعالج وتحلل كل إطار',
    feature3Title: 'احصل على النتائج',
    feature3Text: 'احصل على تقارير مفصلة مع درجات الثقة والبيانات الشرعية',
    
    // Team - Arabic
    teamTitle: 'تم إنشاؤه بواسطة',
    teamText: 'تم تطويره من قبل أماني البرازي وبشرى الشهري ومرام الحسامي',
    courseInfo: 'مشروع التخرج CS 4174',
    supervisor: 'المشرف: د. فداء عابد',
    instructor: 'المدرس: د. نائلة مرير',
    
    // Footer - Arabic
    termsOfService: 'شروط الخدمة',
    privacy: 'سياسة الخصوصية',
    contact: 'اتصل بنا',
    copyright: '© 2025 DeepXpose. جميع الحقوق محفوظة.',
    
    // DetectZone - Arabic
    uploadTitle: 'ارفع فيديو للتحليل',
    uploadSubtitle: 'اسحب وأفلت ملف الفيديو أو انقر للتصفح',
    analyzing: 'جاري التحليل...',
    resultsTitle: 'نتائج التحليل',
    confidence: 'الثقة',
    processingTime: 'وقت المعالجة',
    generateReport: 'إنشاء تقرير',
    
    // Analysis results - Arabic
    real: 'حقيقي',
    fake: 'مزيف',
    riskLow: 'خطر منخفض',
    riskMedium: 'خطر متوسط',
    riskHigh: 'خطر عالي',
    
    // Pricing - Arabic
    pricingTitle: 'اختر خطتك',
    pricingSubtitle: 'اختر الخطة المثالية لاحتياجات كشف التزييف العميق',
    month: '/شهر',
    popular: 'شائع',
    suitable: 'مناسب لـ',
    
    // Help - Arabic
    helpTitle: 'الأسئلة الشائعة',
    helpSubtitle: 'اعثر على إجابات للأسئلة الشائعة حول DeepXpose',
    
    // Additional common text - Arabic
    accuracyRate: 'معدل الدقة',
    avgAnalysis: 'متوسط التحليل',
    videosAnalyzed: 'مقاطع الفيديو المحللة',
    trustedSecurity: 'أمان موثوق',
    trustedSecurityDesc: 'معالجة مشفرة من طرف إلى طرف مع حذف تلقائي للبيانات',
    lightningFast: 'سريع البرق',
    lightningFastDesc: 'تحليل فوري مع نتائج في أقل من 3 ثوان',
    aiPowered: 'مدعوم بالذكاء الاصطناعي',
    aiPoweredDesc: 'نماذج محولات متقدمة بمعدل دقة 96.8%',
    detailedReports: 'تقارير مفصلة',
    detailedReportsDesc: 'تحليل شرعي شامل بصيغ قابلة للتصدير',
    welcomeBack: 'أهلاً بعودتك',
    welcomeBackDesc: 'سجل الدخول إلى حساب DeepXpose للمتابعة في تحليل مقاطع الفيديو',
    createAccount: 'إنشاء حساب',
    createAccountDesc: 'انضم إلى DeepXpose لبدء تحليل مقاطع الفيديو لكشف التزييف العميق',
    continueWithGoogle: 'متابعة مع جوجل',
    signUpWithGoogle: 'إنشاء حساب مع جوجل',
    emailAddress: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    fullName: 'الاسم الكامل',
    accountType: 'نوع الحساب',
    organization: 'المؤسسة (اختياري)',
    confirmPassword: 'تأكيد كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    signUpForFree: 'اشترك مجاناً',
    signInHere: 'سجل الدخول هنا',
    freeTrialIncluded: 'نسخة تجريبية مجانية',
    freeTrialDesc: 'احصل على 5 تحليلات فيديو مجانية لاختبار منصتنا. لا حاجة لبطاقة ائتمان.',
    endUser: 'مستخدم نهائي - تحليل فردي',
    investigator: 'محقق - طب شرعي مهني',
    termsAgreement: 'بإنشاء حساب، فإنك توافق على',
    and: 'و',
    chooseFile: 'اختر ملف',
    supportedFormats: 'الصيغ المدعومة: MP4، MOV، AVI، MKV، WebM',
    uploadProgress: '% تم الرفع',
    viewDetails: 'عرض التفاصيل',
    report: 'تقرير',
    artifactsDetected: 'آثار مكتشفة',
    temporalIssues: 'مشاكل زمنية',
    faceRegions: 'مناطق الوجه',
    analyzeAnotherVideo: 'حلل فيديو آخر',
    newAnalysis: 'تحليل جديد',
    totalAnalyses: 'إجمالي التحليلات',
    analysesRemaining: 'التحليلات المتبقية',
    subscription: 'الاشتراك',
    searchByFilename: 'بحث بالاسم...',
    filterByResult: 'تصفية بالنتيجة',
    allResults: 'جميع النتائج',
    fakeOnly: 'مزيف فقط',
    realOnly: 'حقيقي فقط',
    sortBy: 'ترتيب حسب',
    newestFirst: 'الأحدث أولاً',
    oldestFirst: 'الأقدم أولاً',
    confidenceSort: 'الثقة',
    filename: 'اسم الملف',
    clear: 'مسح',
    noAnalysisFound: 'لم يتم العثور على تحليل',
    noMatchingFilters: 'لا توجد تحليلات تطابق المرشحات الحالية.',
    noAnalysisYet: 'لم تحلل أي مقاطع فيديو بعد.',
    analyzeFirstVideo: 'حلل أول فيديو لك',
    // Additional DetectZone and page-specific translations
    uploadingFile: 'رفع الملف',
    analyzing: 'جاري التحليل...',
    manipulationIndicators: 'مؤشرات التلاعب',
    forensicReport: 'تقرير شرعي',
    executiveSummary: 'ملخص تنفيذي',
    technicalFindings: 'النتائج التقنية',
    recommendations: 'التوصيات',
    downloadReport: 'تحميل التقرير',
    generating: 'جاري الإنشاء...',
    // Report Generation - Arabic
    reportGeneration: 'إنتاج التقرير الشرعي',
    generatingReport: 'جاري إنشاء التقرير...',
    reportReady: 'التقرير جاهز',
    downloadPDF: 'تحميل تقرير PDF',
    backToDetect: 'العودة إلى منطقة الكشف',
    noAnalysisData: 'لا توجد بيانات تحليل',
    completeAnalysis: 'يرجى إكمال تحليل الفيديو أولاً.',
    analysisOverview: 'نظرة عامة على التحليل',
    analystInfo: 'معلومات المحلل',
    analystName: 'اسم المحلل',
    role: 'الدور',
    reportGenerated: 'تم إنشاء التقرير',
    analysisMetadata: 'بيانات التحليل الوصفية',
    reportVersion: 'إصدار التقرير',
    analysisEngine: 'محرك التحليل',
    reportId: 'معرف التقرير',
    generatedAt: 'تم الإنشاء في',
    // Footer translations
    madeWithLove: 'تم الإنشاء بحب من أجل الثقة الرقمية وصحة الوسائط',
    quickLinks: 'روابط سريعة',

    // Nav extra - Arabic
    trendingAnalysis: 'تحليل المحتوى الرائج',
    dashboard: 'لوحة التحكم',
    logout: 'تسجيل الخروج',

    // Home extra - Arabic
    howItWorksSubtitle: 'يعالج نظامنا المدعوم بالذكاء الاصطناعي مقاطع الفيديو عبر طبقات متعددة من التحليل للكشف عن التلاعب بالتزييف العميق.',

    // Trending page - Arabic
    trendingSubtitle: 'حلّل مقاطع الفيديو الرائجة من منصات التواصل الاجتماعي للكشف عن التلاعب بالتزييف العميق والتحقق من الأصالة باستخدام الكشف المدعوم بالذكاء الاصطناعي.',
    realtimeAIDetection: 'كشف فوري بالذكاء الاصطناعي',
    liveSocialMedia: 'وسائل تواصل اجتماعي مباشرة',
    trendingContent: 'محتوى رائج',
    loadingTrendingVideos: 'جاري تحميل مقاطع الفيديو الرائجة',
    loadingTrendingDesc: 'جاري جلب أحدث المحتوى الرائج من منصات التواصل الاجتماعي...',
    analyzingVideoContent: 'تحليل محتوى الفيديو',
    processingWithAI: 'المعالجة باستخدام نماذج الكشف بالذكاء الاصطناعي...',
    analysisIdLabel: 'معرّف التحليل:',
    keyFindingsLabel: 'النتائج الرئيسية:',
    processingTimeLabel: 'وقت المعالجة:',
    checkAuthenticity: 'تحقق من الأصالة',
    reanalyze: 'إعادة التحليل',
    noVideosFound: 'لم يتم العثور على مقاطع فيديو',
    noVideosDesc: 'لا توجد مقاطع فيديو رائجة متاحة للمنصة المحددة. حاول التبديل إلى مرشح آخر.',
    howTrendingWorks: 'كيف يعمل تحليل المحتوى الرائج',
    realtimeMonitoring: 'مراقبة فورية',
    realtimeMonitoringDesc: 'نراقب باستمرار المحتوى الرائج عبر منصات التواصل الاجتماعي الرئيسية.',
    aiAnalysisStep: 'تحليل الذكاء الاصطناعي',
    aiAnalysisStepDesc: 'تحلل نماذج المحولات المتقدمة كل فيديو بحثاً عن مؤشرات التلاعب.',
    instantResultsStep: 'نتائج فورية',
    instantResultsStepDesc: 'احصل على تحقق فوري من الأصالة مع درجات الثقة وتقييم المخاطر.',
    fakeLabel: '❌ مزيف',
    realLabel: '✅ حقيقي',
    fakeMessage: 'يُظهر هذا الفيديو علامات التلاعب.',
    realMessage: 'يبدو هذا الفيديو أصلياً.',
    viewReport: 'عرض التقرير',
    loginToCheck: 'يرجى تسجيل الدخول للتحقق من أصالة الفيديو. جاري التحويل إلى تسجيل الدخول...',
    analysisFailed: 'فشل التحليل. يرجى المحاولة مرة أخرى.',
    failedToLoadVideos: 'فشل تحميل مقاطع الفيديو الرائجة. يرجى المحاولة مرة أخرى.',
    retry: 'إعادة المحاولة',

    // Help page - Arabic
    liveChat: 'دردشة مباشرة',
    liveChatDesc: 'احصل على مساعدة فورية من فريق الدعم لدينا',
    startChat: 'ابدأ الدردشة',
    emailSupport: 'دعم البريد الإلكتروني',
    emailSupportDesc: 'أرسل لنا رسالة مفصلة',
    sendEmail: 'إرسال بريد إلكتروني',
    phoneSupport: 'دعم هاتفي',
    phoneSupportDesc: 'تحدث مباشرة مع خبرائنا',
    callUs: 'اتصل بنا',
    searchHelpPlaceholder: 'ابحث في مقالات المساعدة والأسئلة الشائعة...',
    noResultsFound: 'لم يتم العثور على نتائج',
    noResultsDesc: 'حاول تعديل مصطلحات البحث أو تصفح فئات المساعدة لدينا.',
    helpCategories: 'فئات المساعدة',
    stillNeedHelp: 'ما زلت بحاجة إلى مساعدة؟',
    stillNeedHelpDesc: 'فريق الدعم لدينا متاح على مدار الساعة لمساعدتك في أي أسئلة أو مشكلات.',
    emailLabel: 'البريد الإلكتروني',
    responseWithin2h: 'الرد خلال ساعتين',
    available247: 'متاح على مدار الساعة طوال أيام الأسبوع',
    instantResponse: 'رد فوري',
    phoneLabel: 'الهاتف',
    phoneHours: 'الإثنين-الجمعة، 9 صباحاً - 6 مساءً',
    emergencySupport: 'الدعم الطارئ',
    emergencySupportDesc: 'للمشكلات الأمنية الحرجة أو احتياجات التحليل الشرعي العاجلة، اتصل بخط الدعم الطارئ لدينا.',
    emergencyContact: 'اتصال الطوارئ',
    catGettingStarted: 'البدء',
    catGettingStartedDesc: 'تعلّم أساسيات DeepXpose',
    catTechDocs: 'الوثائق التقنية',
    catTechDocsDesc: 'موارد تقنية متعمقة',
    catSecurity: 'الأمان والخصوصية',
    catSecurityDesc: 'حماية البيانات والأمان',
    catPerformance: 'الأداء والتحسين',
    catPerformanceDesc: 'حسّن سير عمل التحليل لديك',
    art1: 'كيفية إنشاء أول تحليل لك',
    art2: 'فهم درجات الثقة',
    art3: 'صيغ وأحجام الفيديو المدعومة',
    art4: 'إعداد الحساب والتحقق',
    art5: 'وثائق وأمثلة واجهة برمجة التطبيقات',
    art6: 'دليل التكامل للمطورين',
    art7: 'فهم خوارزميات الكشف',
    art8: 'صيغ التقارير المخصصة',
    art9: 'كيف نحمي بياناتك',
    art10: 'معلومات الامتثال للائحة GDPR',
    art11: 'سياسات الاحتفاظ بالبيانات',
    art12: 'أفضل ممارسات الأمان',
    art13: 'تحسين سرعات المعالجة',
    art14: 'نصائح تحسين الملفات',
    art15: 'إرشادات المعالجة الدفعية',
    art16: 'توصيات تحسين الخطة',

    // Form placeholders & misc - Arabic
    enterEmail: 'أدخل بريدك الإلكتروني',
    enterPassword: 'أدخل كلمة المرور',
    enterFullName: 'أدخل اسمك الكامل',
    selectRole: 'اختر دورك',
    enterOrganization: 'أدخل مؤسستك',
    createPassword: 'أنشئ كلمة مرور',
    confirmYourPassword: 'أكّد كلمة المرور',
    signingIn: 'جاري تسجيل الدخول...',
    creatingAccount: 'جاري إنشاء الحساب...',
    viewSampleReport: 'عرض نموذج التقرير',
    tryFreeDemo: 'جرّب العرض المجاني',
    startFreeTrial: 'ابدأ النسخة التجريبية المجانية',
    startDemoAnalysis: 'ابدأ التحليل التجريبي',
    signUpNow: 'سجّل الآن',
    accessRequired: 'تسجيل الدخول مطلوب',
    accessRequiredDesc: 'يرجى تسجيل الدخول لعرض سجل التحليلات الخاص بك.',
    previousAnalysisDesc: 'اعرض وأدر سجل تحليلات كشف التزييف العميق الخاص بك',
    tryBeforeSubscribe: 'جرّب قبل الاشتراك',
    tryBeforeSubscribeDesc: 'اختبر تقنية كشف التزييف العميق لدينا من خلال عرض توضيحي مجاني',
    contactSales: 'اتصل بالمبيعات',
    analysesIncludedSuffix: 'تحليلات مشمولة',
    demoAccount: 'حساب تجريبي:',
    demoFeature: 'ميزة تجريبية',
    tryDemoTitle: 'جرّب العرض التوضيحي لـ DeepXpose',
    tryDemoSubtitle: 'اختبر تقنية كشف التزييف العميق المدعومة بالذكاء الاصطناعي من خلال هذا العرض التفاعلي. شاهد كيف يحلل DeepXpose مقاطع الفيديو بحثاً عن مؤشرات التلاعب.',
    runDemoAgain: 'إعادة تشغيل العرض',
    fileName: 'اسم الملف:',
    fileSize: 'حجم الملف:',
    analysisComplete: 'اكتمل التحليل',
    analysisCompleteEndUser: 'اكتمل تحليل الفيديو الخاص بك. أنشئ تقريراً مفصلاً أدناه.',
    analysisCompleteInvestigator: 'اكتمل التحليل الشرعي المهني. أنشئ تقريراً شاملاً.',
    manipulationIndicatorsDetected: 'تم اكتشاف مؤشرات التلاعب',
    upgradeToInvestigator: 'الترقية إلى محقق للحصول على ميزات شرعية متقدمة',
    faq1Q: 'ما مدى دقة DeepXpose في كشف التزييف العميق؟',
    faq1A: 'يحقق DeepXpose دقة 96.8% على المعايير القياسية باستخدام أحدث نماذج المحولات. يجمع نظامنا بين تحليل الوجه وفحوصات الاتساق الزمني ومزامنة الصوت والصورة لتوفير كشف شامل.',
    faq2Q: 'ما صيغ الفيديو المدعومة؟',
    faq2A: 'ندعم جميع صيغ الفيديو الرئيسية بما في ذلك MP4 وMOV وAVI وMKV وWebM. الحد الأقصى لحجم الملف هو 500 ميجابايت للخطة الأساسية، و2 جيجابايت للخطة الاحترافية، وغير محدود للمؤسسات.',
    faq3Q: 'كم يستغرق التحليل؟',
    faq3A: 'يعتمد وقت التحليل على طول الفيديو ونوع الخطة. الخطة الأساسية: ~3-5 ثوانٍ لكل دقيقة من الفيديو. الخطة الاحترافية: ~1-2 ثانية لكل دقيقة مع معالجة ذات أولوية.',
    faq4Q: 'هل بياناتي آمنة وخاصة؟',
    faq4A: 'نعم، تتم معالجة جميع مقاطع الفيديو المرفوعة بأمان وتُحذف تلقائياً بعد 30 يوماً. نستخدم التشفير من طرف إلى طرف ونلتزم بمعايير الخصوصية الدولية بما في ذلك GDPR.',
    faq5Q: 'هل يمكنني دمج DeepXpose مع أنظمتي الحالية؟',
    faq5A: 'تتضمن الخطط الاحترافية والمؤسسية الوصول إلى واجهة برمجة التطبيقات للتكامل السلس. نوفر وثائق شاملة ودعماً للتكاملات المخصصة.'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('deepxpose-language');
    return saved || 'en';
  });

  const [isRTL, setIsRTL] = useState(language === 'ar');

  useEffect(() => {
    setIsRTL(language === 'ar');
    document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', language);
    localStorage.setItem('deepxpose-language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, isRTL, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};